### ISSUE TITLE
Possible hardware issue?

### ISSUE THREAD

**Issue by cmsj** [nlimper/Mini-AP-v3#1]
Hi!

I purchased a Mini v3 AP from your Tindie store. It joined wifi perfectly and finds tags, but seems to be unable to generate the .raw files for them. When I configure a tag to show any kind of image/counter/date I see a log message of:

```
21:01:47 File has size 0. //00000283A43D3B10.raw
21:01:47 Updating 00000283A43D3B10
21:01:46 Ok, saved
```

at the same time the serial console will output:

```
DB saved 167ms
Failed to allocate buffer
Maximum Continuous Heap Space: 147444
```

I reflashed the device with the ESP32_S3_16_8_YELLOW_AP 2.01b firmware (which I think is the same exact thing that it came with) and this is the boot log. I'm not familiar with the hardware, but maybe the error messages are relevant?

I also opened [an issue](https://github.com/jjwbruijn/OpenEPaperLink/issues/165) in the openepaperlink repo before I saw this boot log.

```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x2a (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a68
entry 0x403c98d4
E (235) opi psram: PSRAM ID read error: 0x00000000, PSRAM chip not found or not supported, or wrong PSRAM line mode
E (235) spiram: SPI RAM enabled but initialization failed. Bailing out.
>
[WiFi-event 0] 
[WiFi-event 2] 
Stored ssid: chrul
[WiFi-event 3] 
[WiFi-event 0] 
Connecting to WiFi...[WiFi-event 2] 

[WiFi-event 4] Connected to access point
[WiFi-event 7] Obtained IP address: 10.0.88.58
Connected!
reading DB from file
loadDB took 252ms
pingACK> ok, 76ms
```

**Comment by nlimper** [comment]
Thanks for researching. It must be a broken esp32-s3 module. I have send you an email to arrange for a replacement.
