### ISSUE TITLE
Unreachable AP

### ISSUE THREAD

**Issue by ScuttleSE** [nlimper/Mini-AP-v3#2]
Today when I got home I noticed that the three eink-devices I had set up with my recently purchased Mini-AP-v3 hadn't been updated.

When I checked in the WebUI, it said that they had been offline for quite some times. First I thought it was the batteries, so I swapped them out with fresh ones in one of the devices. That did not help, so I powercycled the AP.
After that I have not been able to really get it up and running again. It connects to my Wifi, but I have a horrible connection to it, 50% packetloss and an average ping of 800ms to it.

Currently the LED just under the OLED screen is slowly pulsing blue, the three LEDs to the left are all inactive.

I have not tried a complete factory reset of the AP though. Could that be an option, and if so, is there some nice documentation on how to do it? :)

**Comment by ScuttleSE** [comment]
To add, the OLED screen looks like this right now

![image](https://github.com/nlimper/Mini-AP-v3/assets/4344284/a53977ce-1c9c-43c0-a386-6e61f7307afa)

**Comment by nlimper** [comment]
The blue pulsing LED means 'there are tags which tmed out', that are the three that are unreachable.

To reflash the firmware on the AP, you can go to https://install.openepaperlink.de/ (best to use Chrome). Don't connect your AP yet to the computer. First choose 'mini AP v3' and click 'connect'. Now connect your AP, and the com-port shows up. Choose com-port, and click 'install'.

If it doesn't solve the problem, try to change the channel to for example channel 25 (in the config screen of the AP). After changing the channel, reboot the tags (or wait about a day, they will find the new channel eventually).

Hope this all works. If all fails, contact me by email. :-)
